### ISSUE TITLE
une commande ne fonctionne pas

### ISSUE THREAD

**Issue by tana-to** [NewAgeCZ/CommandHook#3]
bonjour le plugin fonctionne bien mais je ne comprends pas pourquoi cette commande ne fonctionne pas : kit give général @a[x=84,y=232,z=33,dx=-11,dy=-11,dz=10,team=general] sachant que j'ai belle et bien créer cette team et que je me suis ajouté dedans. J'ai aussi bien installé la dernier version du plugin et j'ai un serveur 1.16.5 spigot.

**Comment by NewAgeCZ** [comment]
See #4
