### ISSUE TITLE
A command doesn't work

### ISSUE THREAD

**Issue by tana-to** [NewAgeCZ/CommandHook#4]
hello, the plugin works well but I don't understand why this command doesn't work: general give kit @A[x=84,y=232,z=33,dx=-11,dy=-11,dz=10,team=general] knowing that I created this team and added myself to it.  I also installed the latest version of the plugin and I have a 1.16.5 spigot server.

**Comment by NewAgeCZ** [comment]
Stale issue, discussion over discord was made over various other issues.
